// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgk4J72SQ8NcWqSILnxH56wEo4rIl9XjE',
    appId: '1:894988944297:web:340c85ce1f8c80d0b57ab8',
    messagingSenderId: '894988944297',
    projectId: 'medic-87909',
    authDomain: 'medic-87909.firebaseapp.com',
    storageBucket: 'medic-87909.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5S-EUy0ZSNCtTHlDrA-ZzYsyZxoLzTY',
    appId: '1:894988944297:android:ecc0d750b2cab244b57ab8',
    messagingSenderId: '894988944297',
    projectId: 'medic-87909',
    storageBucket: 'medic-87909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRIohUrmXHdVzIYyh4FnOTKoEwJ_5Mqxk',
    appId: '1:894988944297:ios:1790886b2e467135b57ab8',
    messagingSenderId: '894988944297',
    projectId: 'medic-87909',
    storageBucket: 'medic-87909.appspot.com',
    iosBundleId: 'com.corange.medic',
  );
}
